### ISSUE TITLE
AudioRecorder.java file is not working

### ISSUE THREAD

**Issue by SriyanshJainn** [wrandelshofer/MonteMedia#6]
When we run the main method of AudioRecorder.java the program starts running and gets below error:

Exception in thread "Thread-0" java.lang.ClassCastException: org.monte.media.avi.AbstractAVIStream$AudioTrack cannot be cast to org.monte.media.avi.AbstractAVIStream$VideoTrack
	at org.monte.media.avi.AVIOutputStream.getCompressionQuality(AVIOutputStream.java:317)
	at org.monte.media.avi.AVIWriter.createCodec(AVIWriter.java:498)
	at org.monte.media.avi.AVIWriter.write(AVIWriter.java:323)
	at pages_web.AudioRecorder.run(AudioRecorder.java:74)
	at java.lang.Thread.run(Thread.java:748)

**Comment by wrandelshofer** [comment]
I can not reproduce this problem. In which version of MonteMedia do you encounter this problem?

**Comment by wrandelshofer** [comment]
Closing this as I can not reproduce the problem.
